### ISSUE TITLE
Would be nice to have a option to resize for Alliance Flags.

### ISSUE THREAD

**Issue by NarratorNA** [malulleybovo/SymbolArtEditorOnline#13]
So I needed to create an Alliance Flag and tried to use SymbolArtEditor but the size are only for Symbol Arts. I know it was only for Symbol arts but Alliance Flags can also be imported in the game in a similar way. So I'm suggesting to add an option for Alliance Flags.

**Comment by malulleybovo** [comment]
Related to https://github.com/malulleybovo/SymbolArtEditorOnline/issues/11.
The ability to resize groups of symbols as well as Team/Alliance Flag support has been requested before.
These feature requests are currently being evaluated based on how many users desire them since they required substantial rework.

**Comment by RepairUnit3k6** [comment]
> being evaluated based on how many users desire
Problem is that people won't come to github issues and mention they would like this feature. Majority of people have no fucking clue what github is, let alone how to use it. This feature is wanted by people, they just have no clue how to tell you it. Most people just shrug and leave looking for alternative that have this feature

**Comment by RepairUnit3k6** [comment]
I did some playing around. Besides colors being completely fucked up which you are aware of as of #14 game seems to accept any symbol art of correct size. Alliance flags are this big. Just add some guidelines so people know how big to make alliance flags, like literally just draw 4 lines to give people indication of how big they can make alliance flags
![lXXbWcvUo0](https://user-images.githubusercontent.com/24418090/110834784-450f3400-829e-11eb-94fd-0540ec220e1b.png)

**Comment by malulleybovo** [comment]
Your troubles have been heard. The incoming release will add support for Alliance (Team) flag as well as regular Symbol Art, along with a brand new user interface with faster loading time, more fluid interaction and controls. Stay tuned.
