### ISSUE TITLE
RangeError: Maximum call stack size exceeded when trying to upload .saml file

### ISSUE THREAD

**Issue by Atidhaya** [malulleybovo/SymbolArtEditorOnline#16]
I was under the process of making SA and as the readme suggests, I want to save my progress so I download my progress as the .saml file. 

To verify the downloaded file, I open another tab and upload back the file and it results in possibly infinite loop/recursion. 

The same SA but .sar seems to work fine though. 

stack trace under console.

`
Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at klass.setupOverlay (samlloader.js:643)
    at klass.load (samlloader.js:39)
    at FileReader.reader.onload (main.js:865)
load @ samlloader.js:143
reader.onload @ main.js:865
load (async)
(anonymous) @ main.js:859
setTimeout (async)
(anonymous) @ main.js:857
dispatch @ jquery-1.11.3.min.js:4
r.handle @ jquery-1.11.3.min.js:4`

just in case you need this, it's the .saml file of under progress SA.

https://file.io/AfiW5FeI1EqE

**Comment by malulleybovo** [comment]
Hello and thank you for reporting.

Do you perhaps still have a copy of the damaged SAML file? The link above was deleted.

**Comment by malulleybovo** [comment]
If you still have the damaged file, please try to load it using v2.0.0 of the application.

Feel free to reopen this issue if the problem persists.
