### ISSUE TITLE
.SAR Does Not Import

### ISSUE THREAD

**Issue by Keysuru** [malulleybovo/SymbolArtEditorOnline#18]
Clicking the + icon to import a proper .sar file, it will not rebuild itself in the editor as it used to.

I've built a total of 10 SA's using this tool. It's 1,000% useful. Please look into this.

**Comment by malulleybovo** [comment]
Hello, thanks for reporting.

The + icon in the landing page of the editor starts a new symbol art from scratch. The button to import a .sar file from your computer is the one in the landing page next to the + icon: the icon with an arrow pointing up. For visual reference, check out [https://github.com/malulleybovo/SymbolArtEditorOnline/wiki/1.1-Features-Part-1](https://github.com/malulleybovo/SymbolArtEditorOnline/wiki/1.1-Features-Part-1). Let me know if this solves the issue.

A better news is that this version of the editor will soon retire and another will take its place including much improved performance, accuracy, and usability.

**Comment by malulleybovo** [comment]
Please use v2.0.0 to check if the issue persists.

Feel free to reopen this issue should it reappear.
