### ISSUE TITLE
Team Flag Symbol limit

### ISSUE THREAD

**Issue by dynlazybones** [malulleybovo/SymbolArtEditorOnline#20]
First of all, thank you very much for your work, i really enjoy using this. After used your SA Editor for more than 2 weeks, i find that it's a lot easier to Trace the picture into SA but i also find that click and hold function to select not work excactly as expect, hit and missed a lot. Many times i just want to move or edit a symbol but miss hit navigator then lost the control and have to go back to side view to select again. So i think if there is a way to disable "click and hold to select" function.

Second, the main issue i want to talk is the limit of symbol in Team Flag, as i can see it only 25 symbols limit even though ingame is 225, same as standard. So i want to ask that did i miss some setting ? or how does actually the team flag function work ?

Thank you for your attention and sorry for my English

**Comment by malulleybovo** [comment]
Hello,

In v2.0.0, there isn’t a way to disable tap and hold. It’s a core mechanic. I’m evaluation some changes that may allow for that though. Something along the line of a toggle button, linked to the “shift” key. But that is subject to change.

Regarding the team flag (alliance flag) limit, you are absolutely right. The limit is wrong. It should be 225. Check out v2.0.1 for this. Thanks for letting me know!

**Comment by malulleybovo** [comment]
Please check out the newest release, which includes improvements based on user feedback.

https://github.com/malulleybovo/SymbolArtEditorOnline/releases/tag/v2.1.0

Feel free to reopen the issue or create a new one for further discussion.
